version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    dotnet --version

    dotnet restore ./src/Mockaco/Mockaco.csproj --verbosity m

    dotnet publish ./src/Mockaco/Mockaco.csproj
test_script:
- cmd: dotnet test .\test\Mockaco.Tests\Mockaco.Tests.csproj
artifacts:
- path: src\Mockaco\bin\Release\netcoreapp2.2\publish\
  name: Mockaco Web Site
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  auth_token:
    secure: /I2jw4WdsgmkOPWZ/Xaoht8/eQ4W+dOP+H8jwMnzO7tNt3AsDoDhuJg4ClZuQT9v
  artifact: Mockaco Web Site
  draft: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
