name: ASP.NET Core CI


on:
  workflow_dispatch:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0      
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:         
          dotnet-version: '5.0.x'
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create nupkg
        run: dotnet pack --configuration Nuget --output ./nupkg
      - name: Publish nupkg
        run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json